// Code generated by go generate; DO NOT EDIT.

package lua

import (
	"context"
	"fmt"
	"github.com/redis/go-redis/v9"
)

// IsJobInListScript is the isJobInList script, exported so callers can
// run it inside pipelines/transactions (EVALSHA after Load).
var IsJobInListScript = redis.NewScript(`--[[
  Checks if job is in a given list.
  Input:
    KEYS[1]
    ARGV[1]
  Output:
    1 if element found in the list.
]]
-- Includes
--[[
  Functions to check if a item belongs to a list.
]]
local function checkItemInList(list, item)
  for _, v in pairs(list) do
    if v == item then
      return 1
    end
  end
  return nil
end
local items = redis.call("LRANGE", KEYS[1] , 0, -1)
return checkItemInList(items, ARGV[1])
`)

// IsJobInList executes the Lua script isJobInList on Redis with 1 keys.
func IsJobInList(ctx context.Context, client redis.Cmdable, keys []string, args ...any) (any, error) {
	if len(keys) != 1 {
		return nil, fmt.Errorf("expected 1 keys but got %d", len(keys))
	}
	result, err := IsJobInListScript.Run(ctx, client, keys, args...).Result()
	if err != nil {
		return nil, err
	}
	return result, nil
}
