// Code generated by go generate; DO NOT EDIT.

package lua

import (
	"context"
	"fmt"
	"github.com/redis/go-redis/v9"
)

// PauseScript is the pause script, exported so callers can
// run it inside pipelines/transactions (EVALSHA after Load).
var PauseScript = redis.NewScript(`--[[
  Pauses or resumes a queue globably.
  Input:
    KEYS[1] 'wait' or 'paused''
    KEYS[2] 'paused' or 'wait'
    KEYS[3] 'meta'
    KEYS[4] 'prioritized'
    KEYS[5] events stream key
    ARGV[1] 'paused' or 'resumed'
  Event:
    publish paused or resumed event.
]]
local rcall = redis.call
-- Includes
--[[
  Function priority marker to wait if needed
  in order to wake up our workers and to respect priority
  order as much as possible
]]
local function addPriorityMarkerIfNeeded(waitKey)
  local waitLen = rcall("LLEN", waitKey)
  if waitLen == 0 then
    rcall("LPUSH", waitKey, "0:0")
  end
end
if rcall("EXISTS", KEYS[1]) == 1 then
  rcall("RENAME", KEYS[1], KEYS[2])
end
if ARGV[1] == "paused" then
  rcall("HSET", KEYS[3], "paused", 1)
else
  rcall("HDEL", KEYS[3], "paused")
  local priorityCount = rcall("ZCARD", KEYS[4])
  if priorityCount > 0 then
    addPriorityMarkerIfNeeded(KEYS[2])
  end
end
rcall("XADD", KEYS[5], "*", "event", ARGV[1]);
`)

// Pause executes the Lua script pause on Redis with 5 keys.
func Pause(ctx context.Context, client redis.Cmdable, keys []string, args ...any) (any, error) {
	if len(keys) != 5 {
		return nil, fmt.Errorf("expected 5 keys but got %d", len(keys))
	}
	result, err := PauseScript.Run(ctx, client, keys, args...).Result()
	if err != nil {
		return nil, err
	}
	return result, nil
}
