// Code generated by go generate; DO NOT EDIT.

package lua

import (
	"context"
	"fmt"
	"github.com/redis/go-redis/v9"
)

// ReleaseLockScript is the releaseLock script, exported so callers can
// run it inside pipelines/transactions (EVALSHA after Load).
var ReleaseLockScript = redis.NewScript(`--[[
  Release lock
    Input:
      KEYS[1] 'lock',
      ARGV[1]  token
      ARGV[2]  lock duration in milliseconds
    Output:
      "OK" if lock extented succesfully.
]]
local rcall = redis.call
if rcall("GET", KEYS[1]) == ARGV[1] then
  return rcall("DEL", KEYS[1])
else
  return 0
end
`)

// ReleaseLock executes the Lua script releaseLock on Redis with 1 keys.
func ReleaseLock(ctx context.Context, client redis.Cmdable, keys []string, args ...any) (any, error) {
	if len(keys) != 1 {
		return nil, fmt.Errorf("expected 1 keys but got %d", len(keys))
	}
	result, err := ReleaseLockScript.Run(ctx, client, keys, args...).Result()
	if err != nil {
		return nil, err
	}
	return result, nil
}
