// Code generated by go generate; DO NOT EDIT.

package lua

import (
	"context"
	"fmt"
	"github.com/redis/go-redis/v9"
)

// UpdateDataScript is the updateData script, exported so callers can
// run it inside pipelines/transactions (EVALSHA after Load).
var UpdateDataScript = redis.NewScript(`--[[
  Update job data
  Input:
    KEYS[1] Job id key
    ARGV[1] data
  Output:
    0 - OK
   -1 - Missing job.
]]
local rcall = redis.call
if rcall("EXISTS",KEYS[1]) == 1 then -- // Make sure job exists
  rcall("HSET", KEYS[1], "data", ARGV[1])
  return 0
else
  return -1
end
`)

// UpdateData executes the Lua script updateData on Redis with 1 keys.
func UpdateData(ctx context.Context, client redis.Cmdable, keys []string, args ...any) (any, error) {
	if len(keys) != 1 {
		return nil, fmt.Errorf("expected 1 keys but got %d", len(keys))
	}
	result, err := UpdateDataScript.Run(ctx, client, keys, args...).Result()
	if err != nil {
		return nil, err
	}
	return result, nil
}
